"""
Full end-to-end essay grading pipeline test with Groq
Run: pytest backend/tests/test_full_pipeline.py -v -s
"""

import pytest
import asyncio
from app.services.essay_evaluator import EssayEvaluationEngine
from app.db.mongo import db


def test_full_essay_evaluation_pipeline():
    """Complete essay grading pipeline using Groq"""
    async def run_test():
        engine = EssayEvaluationEngine(db)
        
        essay = """
        The Indian Constitution, adopted on January 26, 1950, is a remarkable document that establishes India as a sovereign democratic republic.
        Drafted by the Constituent Assembly under the chairmanship of Dr. B.R. Ambedkar, the Constitution represents a unique synthesis of democratic ideals and Indian values.
        
        The Constitution guarantees fundamental rights to all citizens, including freedom of speech, religion, and equality before law.
        These rights are protected by an independent judiciary that can strike down any law violating constitutional provisions.
        
        The separation of powers among the executive, legislative, and judicial branches ensures effective checks and balances.
        The President is the head of state while the Prime Minister heads the government, following the Westminster model.
        The bicameral Parliament comprises the Lok Sabha (lower house) and the Rajya Sabha (upper house).
        
        Furthermore, the Constitution accommodates India's diversity through federalism and the recognition of regional languages.
        The judicial review power of the Supreme Court has been instrumental in protecting constitutional values and citizens' rights.
        Therefore, the Indian Constitution stands as one of the longest and most comprehensive written constitutions in the world.
        """
        
        question = "Analyze the salient features and importance of the Indian Constitution in establishing democratic governance"
        subject = "political-science"
        
        print(f"\n{'='*70}")
        print(f"ESSAY EVALUATION TEST (Groq + OpenAI Embeddings)")
        print(f"{'='*70}")
        print(f"\nQuestion: {question}")
        print(f"Subject: {subject}")
        print(f"Essay Length: {len(essay)} characters\n")
        
        # Run full evaluation with Groq LLM
        result = await engine.grade_essay(
            essay_text=essay,
            question=question,
            subject=subject
        )
        
        # Validate structure
        assert "grade" in result
        assert "scoring" in result
        assert "phase_0_shadow_rubric" in result
        assert "phase_1_extraction" in result
        assert "phase_2_agents" in result
        
        # Print results
        print(f"\n{'='*70}")
        print(f"EVALUATION RESULTS")
        print(f"{'='*70}")
        
        scoring = result["scoring"]
        print(f"\n📊 SCORING BREAKDOWN:")
        print(f"  Fact Accuracy Score: {scoring['fact_accuracy_score']:.2f}")
        print(f"  Coverage Score: {scoring['coverage_score']:.2f}")
        print(f"  Content Score: {scoring['content_score']:.2f}")
        print(f"  Logical Flow: {scoring['logical_flow']:.2f}")
        print(f"  Language Score: {scoring['language_score']:.2f}")
        print(f"  Raw Score: {scoring['raw_score']:.2f}")
        print(f"  Contradiction Penalty: -{scoring['contradiction_penalty']:.2f}")
        print(f"  Final Score: {scoring['final_score']:.2f}")
        print(f"  Normalized (0-1600): {scoring['normalized_score_0_1600']:.2f}")
        
        print(f"\n🎯 GRADE: {result['grade']}")
        print(f"\n💡 FEEDBACK: {result['feedback']}")
        
        # Phase 0: Shadow Rubric
        phase_0 = result["phase_0_shadow_rubric"]
        print(f"\n{'='*70}")
        print(f"PHASE 0: SHADOW RUBRIC (Generated by Groq)")
        print(f"{'='*70}")
        print(f"Must-Have Concepts ({phase_0.get('concept_count', 0)}):")
        for i, concept in enumerate(phase_0.get("concepts", [])[:10], 1):
            print(f"  {i}. {concept}")
        if len(phase_0.get("concepts", [])) > 10:
            print(f"  ... and {len(phase_0.get('concepts', [])) - 10} more")
        
        # Phase 1: Extraction
        phase_1 = result["phase_1_extraction"]
        print(f"\n{'='*70}")
        print(f"PHASE 1: EXTRACTION & PARSING (Groq)")
        print(f"{'='*70}")
        print(f"Atomic Claims ({phase_1.get('claim_count', 0)}):")
        for i, claim in enumerate(phase_1.get("claims", [])[:5], 1):
            print(f"  {i}. {claim[:60]}...")
        
        print(f"\nDiscourse Markers Detected:")
        for marker_type, count in phase_1.get("discourse_markers", {}).items():
            if count > 0:
                print(f"  {marker_type}: {count}")
        
        # Phase 2: Agents
        phase_2 = result["phase_2_agents"]
        print(f"\n{'='*70}")
        print(f"PHASE 2: MULTI-AGENT ANALYSIS (Groq + OpenAI)")
        print(f"{'='*70}")
        
        # Fact Checker
        fact_result = phase_2["fact_checker"]
        print(f"\n🔍 FACT CHECKER AGENT:")
        print(f"  Accuracy Score: {fact_result['accuracy_score']:.2f}%")
        print(f"  Claims Verified: {fact_result['supported_count']}/{fact_result['total_claims']}")
        print(f"  Contradictions Found: {fact_result['contradiction_count']}")
        
        # Content Coverage
        coverage_result = phase_2["content_coverage"]
        print(f"\n📚 CONTENT COVERAGE AGENT:")
        print(f"  Coverage Score: {coverage_result['coverage_score']:.2f}%")
        print(f"  Concepts Covered: {coverage_result['concepts_covered']}/{coverage_result['total_concepts']}")
        
        # Linguistic
        linguistic_result = phase_2["linguistic"]
        print(f"\n✍️  LINGUISTIC AGENT:")
        print(f"  Grammar Score: {linguistic_result['grammar_score']}")
        print(f"  Vocabulary Score: {linguistic_result['vocabulary_score']}")
        print(f"  Tone Score: {linguistic_result['tone_score']}")
        print(f"  Language Score: {linguistic_result['language_score']:.2f}")
        
        print(f"\n{'='*70}")
        print(f"✓ Full pipeline test completed successfully")
        print(f"{'='*70}\n")
    
    asyncio.run(run_test())


def test_shadow_rubric_generation():
    """Test shadow rubric generation from Pinecone retrieval"""
    async def run_test():
        engine = EssayEvaluationEngine(db)
        
        question = "Explain the federal structure of Indian governance"
        subject = "political-science"
        
        print(f"\n{'='*70}")
        print(f"SHADOW RUBRIC TEST")
        print(f"{'='*70}")
        print(f"\nQuestion: {question}")
        print(f"Subject: {subject}\n")
        
        result = await engine.create_shadow_rubric(question, subject)
            
        if result.get("status") in ["success", "warning"]:
                concepts = result.get("concepts", [])
                print(f"✓ Shadow Rubric Generated with {len(concepts)} concepts:")
                for i, concept in enumerate(concepts, 1):
                    print(f"  {i}. {concept}")
        else:
                print(f"⚠️ {result.get('status')}: {result.get('message', 'Unknown error')}")
    
    asyncio.run(run_test())


def test_pinecone_vector_search():
    """Test Pinecone vector search integration"""
    async def run_test():
        engine = EssayEvaluationEngine(db)
        
        queries = [
            ("What are fundamental rights?", "political-science"),
            ("Explain monsoon patterns", "geography"),
            ("Rise of nationalism in India", "history"),
        ]
        
        print(f"\n{'='*70}")
        print(f"PINECONE VECTOR SEARCH TEST")
        print(f"{'='*70}\n")
        
        for query, subject in queries:
            print(f"🔍 Query: '{query}'")
            print(f"   Subject: {subject}")
            
            results = await engine._query_pinecone(query, subject, top_k=3)
            
            if results:
                print(f"   ✓ Found {len(results)} results:")
                for i, doc in enumerate(results, 1):
                    topic = doc.get("topic", "N/A")
                    score = doc.get("score", 0)
                    print(f"     {i}. {topic} (score: {score:.3f})")
            else:
                print(f"   ⚠️  No results found (index not yet populated)")
            print()
    
    asyncio.run(run_test())


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
